/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.xwiki.contrib.rendering.markdown.commonmark12.internal.parser;

import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.xwiki.component.manager.ComponentLookupException;
import org.xwiki.component.manager.ComponentManager;
import org.xwiki.rendering.listener.Listener;
import org.xwiki.rendering.listener.reference.ResourceReference;
import org.xwiki.rendering.listener.reference.ResourceType;
import org.xwiki.rendering.parser.ResourceReferenceParser;
import org.xwiki.rendering.renderer.PrintRendererFactory;
import org.xwiki.rendering.renderer.reference.link.URILabelGenerator;

import com.vladsch.flexmark.ast.Image;
import com.vladsch.flexmark.ast.ImageRef;
import com.vladsch.flexmark.ast.Reference;
import com.vladsch.flexmark.ext.wikilink.WikiImage;
import com.vladsch.flexmark.util.ast.NodeVisitor;
import com.vladsch.flexmark.util.ast.VisitHandler;

/**
 * Handle image events.
 *
 * @version $Id$
 * @since 8.4
 */
public class ImageNodeVisitor extends AbstractNodeVisitor
{
    static <V extends ImageNodeVisitor> VisitHandler<?>[] VISIT_HANDLERS(final V visitor)
    {
        return new VisitHandler<?>[] {
            new VisitHandler<>(Image.class, node -> visitor.visit(node)),
            new VisitHandler<>(ImageRef.class, node -> visitor.visit(node)),
            new VisitHandler<>(WikiImage.class, node -> visitor.visit(node))
        };
    }

    private ResourceReferenceParser imageResourceReferenceParser;

    private ComponentManager componentManager;

    public ImageNodeVisitor(NodeVisitor visitor, Deque<Listener> listeners,
        ResourceReferenceParser imageResourceReferenceParser, ComponentManager componentManager,
        PrintRendererFactory plainRendererFactory)
    {
        super(visitor, listeners, plainRendererFactory);
        this.imageResourceReferenceParser = imageResourceReferenceParser;
        this.componentManager = componentManager;
    }

    public void visit(Image node)
    {
        // We consider all images to be referencing an URL
        ResourceReference reference = new ResourceReference(node.getUrl().toString(), ResourceType.URL);
        reference.setTyped(false);

        Map<String, String> parameters = new HashMap<>();

        // Handle alt text. Note that in order to have the same behavior as the XWiki Syntax 2.0+ we don't add the alt
        // parameter if its content is the same as the one that would be automatically generated by the XHTML Renderer.
        String computedAltValue = computeAltAttributeValue(reference);
        String extractedAltValue = extractText(node);
        if (StringUtils.isNotEmpty(extractedAltValue) && !extractedAltValue.equals(computedAltValue)) {
            parameters.put("alt", extractedAltValue);
        }

        // Handle optional title
        addTitle(parameters, node.getTitle().toString());

        getListener().onImage(reference, false, parameters);
    }

    public void visit(ImageRef node)
    {
        if (!node.isDefined()) {
            // Non-existing reference, output the image reference as is, as plain text, e.g. "![image.png][invalidref]".
            getListener().onVerbatim(node.getChars().unescape(), true, Collections.emptyMap());
        } else {
            // Since XWiki doesn't support reference images, we generate a standard image instead
            // We consider all images to be referencing an URL
            Reference reference = node.getReferenceNode(getReferenceRepository());
            ResourceReference resourceReference =
                new ResourceReference(reference.getUrl().toString(), ResourceType.URL);
            resourceReference.setTyped(false);

            // Handle an optional image title
            Map<String, String> parameters = Collections.emptyMap();
            if (StringUtils.isNotEmpty(reference.getTitle())) {
                parameters = Collections.singletonMap(TITLE_ATTRIBUTE, reference.getTitle().toString());
            }

            getListener().onImage(resourceReference, false, parameters);
        }
    }

    public void visit(WikiImage node)
    {
        ResourceReference reference = this.imageResourceReferenceParser.parse(node.getLink().toString());
        Map<String, String> parameters = new HashMap<>();

        // Handle alt text. Note that in order to have the same behavior as the XWiki Syntax 2.0+ we don't add the alt
        // parameter if its content is the same as the one that would be automatically generated by the XHTML Renderer.
        String computedAltValue = computeAltAttributeValue(reference);
        if(node.getText() != null) {
            String extractedAltValue = node.getText().toString();
            if (StringUtils.isNotEmpty(extractedAltValue) && !extractedAltValue.equals(computedAltValue)) {
                parameters.put("alt", extractedAltValue);
            }
        }

        getListener().onImage(reference, false, parameters);
    }

    /**
     * @param reference the reference for which to compute the alt attribute value
     * @return the alt attribute value that would get generated if not specified by the user
     */
    private String computeAltAttributeValue(ResourceReference reference)
    {
        String label;
        try {
            URILabelGenerator uriLabelGenerator = this.componentManager.getInstance(URILabelGenerator.class,
                reference.getType().getScheme());
            label = uriLabelGenerator.generateLabel(reference);
        } catch (ComponentLookupException e) {
            label = reference.getReference();
        }
        return label;
    }
}
